blank_issues_enabled: false
contact_links:
  - name: Question
    about: If you have any questions, please visit our GitHub discussions page.
    url: https://github.com/sectasy0/zcached/discussions/categories/q-a
