name: "Install zig"
description: "Downloads and extracts zig compiler"

runs:
  using: "composite"
  steps:
    - name: Install zig 0.14.1
      run: |
        curl -sSfL https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz | tar -xJ
      shell: bash
    - name: Add zig to PATH
      run: echo "${{ github.workspace }}/zig-x86_64-linux-0.14.1" >> $GITHUB_PATH
      shell: bash
