name: zcached end-to-end tests

on:
  push:
    paths-ignore:
      - "**/README.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install zig
      uses: ./.github/actions/install

    - name: Lint code
      uses: ./.github/actions/lint

    - name: Run end-to-end tests
      run: zig build e2e
